manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zlee1
      url-base: https://github.com/zlee1
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zlee1
      import: app/west.yml
  self:
    path: config 
